Layout/LineLength:
  Max: 160
  IgnoredPatterns:
    - .unknown
    - .fatal
    - .error
    - .warn
    - .info
    - .debug
    - .trace
Metrics:
  IgnorePatterns:
    - .unknown
    - .fatal
    - .error
    - .warn
    - .info
    - .debug
    - .trace
Metrics/MethodLength:
  Max: 50
  IgnoredMethods:
    - .unknown
    - .fatal
    - .error
    - .warn
    - .info
    - .debug
    - .trace
Metrics/ClassLength:
  Max: 1500
Metrics/ModuleLength:
  Max: 1500
Metrics/BlockLength:
  Max: 40
  IgnoredMethods:
    - .unknown
    - .fatal
    - .error
    - .warn
    - .info
    - .debug
    - .trace
Metrics/AbcSize:
  Max: 60
  IgnoredMethods:
    - .unknown
    - .fatal
    - .error
    - .warn
    - .info
    - .debug
    - .trace
Metrics/CyclomaticComplexity:
  Max: 15
  IgnoredMethods:
    - .unknown
    - .fatal
    - .error
    - .warn
    - .info
    - .debug
    - .trace
Metrics/PerceivedComplexity:
  Max: 17
  IgnoredMethods:
    - .unknown
    - .fatal
    - .error
    - .warn
    - .info
    - .debug
    - .trace
Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: space
Style/SymbolArray:
  Enabled: true
Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table
Style/Documentation:
  Enabled: false
AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable
  SuggestExtensions: false
Style/FrozenStringLiteralComment:
  Enabled: false
Naming/FileName:
  Enabled: false
