apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "legion.fullname" . }}-worker
  labels:
    {{- include "legion.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      {{- include "legion.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        {{- include "legion.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: worker
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["bundle", "exec", "legion", "start"]
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
          env:
            - name: LEGION_TRANSPORT_HOST
              value: {{ .Values.rabbitmq.host | quote }}
            - name: LEGION_TRANSPORT_PORT
              value: {{ .Values.rabbitmq.port | quote }}
            - name: LEGION_DATA_URL
              value: "postgres://$(DB_USER):$(DB_PASS)@{{ .Values.postgresql.host }}:{{ .Values.postgresql.port }}/{{ .Values.postgresql.database }}"
            {{- with .Values.worker.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          envFrom:
            - secretRef:
                name: {{ .Values.rabbitmq.existingSecret }}
            - secretRef:
                name: {{ .Values.postgresql.existingSecret }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
