apiVersion: v1
kind: Service
metadata:
  name: {{ include "legion.fullname" . }}-api
  labels:
    {{- include "legion.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.port }}
      targetPort: {{ .Values.api.port }}
      protocol: TCP
  selector:
    {{- include "legion.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
