#!/usr/bin/env ruby
# frozen_string_literal: true

RubyVM::YJIT.enable if defined?(RubyVM::YJIT)

ENV['RUBY_GC_HEAP_INIT_SLOTS'] ||= '600000'
ENV['RUBY_GC_HEAP_FREE_SLOTS_MIN_RATIO'] ||= '0.20'
ENV['RUBY_GC_HEAP_FREE_SLOTS_MAX_RATIO'] ||= '0.40'
ENV['RUBY_GC_MALLOC_LIMIT'] ||= '64000000'
ENV['RUBY_GC_MALLOC_LIMIT_MAX'] ||= '128000000'

if ENV['LEGION_BOOTSNAP'] == 'true' && Dir.exist?(File.expand_path('~/.legionio'))
  require 'bootsnap'
  Bootsnap.setup(
    cache_dir:          File.expand_path('~/.legionio/cache/bootsnap'),
    development_mode:   false,
    load_path_cache:    true,
    compile_cache_iseq: true,
    compile_cache_yaml: true
  )
end

$LOAD_PATH.unshift(File.expand_path('../lib', __dir__))

require 'legion/cli'
Legion::CLI::Main.start(ARGV)
