# bash completion for the legionio CLI (daemon lifecycle + all operational commands)
# Generated by LegionIO
#
# Installation:
#   # One-time (current session):
#   source <(legionio completion bash)
#
#   # Permanent (add to ~/.bashrc or ~/.bash_profile):
#   echo 'source <(legionio completion bash)' >> ~/.bashrc
#
#   # Or copy to bash completions directory:
#   legionio completion bash > /etc/bash_completion.d/legionio
#   # macOS with bash-completion@2:
#   legionio completion bash > $(brew --prefix)/etc/bash_completion.d/legionio
#
# Note: `legionio` is the full operational CLI — daemon lifecycle + all 40+ subcommands.
#       Use `legion` for the interactive TTY shell and dev-workflow commands.

_legionio_complete() {
  local cur prev words cword
  _init_completion 2>/dev/null || {
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"
    words=("${COMP_WORDS[@]}")
    cword=$COMP_CWORD
  }

  local top_commands="start stop status check version lex task chain config generate mcp worker coldstart chat memory plan swarm commit pr review gaia schedule completion tree ask dream"
  local global_flags="--json --no-color --verbose --config-dir --help"

  # Top-level command
  if [[ $cword -eq 1 ]]; then
    COMPREPLY=($(compgen -W "${top_commands}" -- "${cur}"))
    return 0
  fi

  local cmd="${words[1]}"

  # Subcommand completions
  case "${cmd}" in
    lex)
      if [[ $cword -eq 2 ]]; then
        COMPREPLY=($(compgen -W "list info create enable disable" -- "${cur}"))
      else
        case "${words[2]}" in
          list)    COMPREPLY=($(compgen -W "--all --json --no-color --help" -- "${cur}")) ;;
          info)    COMPREPLY=($(compgen -W "--json --no-color --help" -- "${cur}")) ;;
          create)  COMPREPLY=($(compgen -W "--rspec --no-rspec --github-ci --no-github-ci --git-init --no-git-init --bundle-install --no-bundle-install --help" -- "${cur}")) ;;
          enable)  COMPREPLY=($(compgen -W "--json --no-color --help" -- "${cur}")) ;;
          disable) COMPREPLY=($(compgen -W "--json --no-color --help" -- "${cur}")) ;;
        esac
      fi
      ;;

    task)
      if [[ $cword -eq 2 ]]; then
        COMPREPLY=($(compgen -W "list show logs run purge" -- "${cur}"))
      else
        case "${words[2]}" in
          list)  COMPREPLY=($(compgen -W "--limit --status --extension --json --no-color --help" -- "${cur}")) ;;
          show)  COMPREPLY=($(compgen -W "--json --no-color --help" -- "${cur}")) ;;
          logs)  COMPREPLY=($(compgen -W "--limit --json --no-color --help" -- "${cur}")) ;;
          run)   COMPREPLY=($(compgen -W "--extension --runner --function --delay --json --no-color --help" -- "${cur}")) ;;
          purge) COMPREPLY=($(compgen -W "--days --confirm --json --no-color --help" -- "${cur}")) ;;
        esac
      fi
      ;;

    chain)
      if [[ $cword -eq 2 ]]; then
        COMPREPLY=($(compgen -W "list create delete" -- "${cur}"))
      else
        case "${words[2]}" in
          list)   COMPREPLY=($(compgen -W "--limit --json --no-color --help" -- "${cur}")) ;;
          create) COMPREPLY=($(compgen -W "--json --no-color --help" -- "${cur}")) ;;
          delete) COMPREPLY=($(compgen -W "--confirm --json --no-color --help" -- "${cur}")) ;;
        esac
      fi
      ;;

    config)
      if [[ $cword -eq 2 ]]; then
        COMPREPLY=($(compgen -W "show path validate scaffold" -- "${cur}"))
      else
        case "${words[2]}" in
          show)     COMPREPLY=($(compgen -W "--section --json --no-color --help" -- "${cur}")) ;;
          path)     COMPREPLY=($(compgen -W "--json --no-color --help" -- "${cur}")) ;;
          validate) COMPREPLY=($(compgen -W "--json --no-color --help" -- "${cur}")) ;;
          scaffold) COMPREPLY=($(compgen -W "--dir --only --full --force --json --no-color --help" -- "${cur}")) ;;
        esac
      fi
      ;;

    generate|g)
      if [[ $cword -eq 2 ]]; then
        COMPREPLY=($(compgen -W "runner actor exchange queue message tool" -- "${cur}"))
      else
        case "${words[2]}" in
          runner)   COMPREPLY=($(compgen -W "--functions --help" -- "${cur}")) ;;
          actor)    COMPREPLY=($(compgen -W "--type --runner --interval --help" -- "${cur}")) ;;
          exchange) COMPREPLY=($(compgen -W "--help" -- "${cur}")) ;;
          queue)    COMPREPLY=($(compgen -W "--exchange --help" -- "${cur}")) ;;
          message)  COMPREPLY=($(compgen -W "--help" -- "${cur}")) ;;
          tool)     COMPREPLY=($(compgen -W "--help" -- "${cur}")) ;;
        esac
      fi
      ;;

    mcp)
      if [[ $cword -eq 2 ]]; then
        COMPREPLY=($(compgen -W "stdio http" -- "${cur}"))
      else
        case "${words[2]}" in
          stdio) COMPREPLY=($(compgen -W "--help" -- "${cur}")) ;;
          http)  COMPREPLY=($(compgen -W "--port --host --help" -- "${cur}")) ;;
        esac
      fi
      ;;

    worker)
      if [[ $cword -eq 2 ]]; then
        COMPREPLY=($(compgen -W "list show pause retire terminate activate costs" -- "${cur}"))
      else
        case "${words[2]}" in
          list)      COMPREPLY=($(compgen -W "--team --owner --state --limit --json --no-color --help" -- "${cur}")) ;;
          show)      COMPREPLY=($(compgen -W "--json --no-color --help" -- "${cur}")) ;;
          pause)     COMPREPLY=($(compgen -W "--reason --json --no-color --help" -- "${cur}")) ;;
          retire)    COMPREPLY=($(compgen -W "--reason --json --no-color --help" -- "${cur}")) ;;
          terminate) COMPREPLY=($(compgen -W "--reason --yes --json --no-color --help" -- "${cur}")) ;;
          activate)  COMPREPLY=($(compgen -W "--json --no-color --help" -- "${cur}")) ;;
          costs)     COMPREPLY=($(compgen -W "--period --json --no-color --help" -- "${cur}")) ;;
        esac
      fi
      ;;

    coldstart)
      if [[ $cword -eq 2 ]]; then
        COMPREPLY=($(compgen -W "ingest preview status" -- "${cur}"))
      else
        case "${words[2]}" in
          ingest)  COMPREPLY=($(compgen -W "--dry-run --pattern --json --no-color --help" -- "${cur}")) ;;
          preview) COMPREPLY=($(compgen -W "--json --no-color --help" -- "${cur}")) ;;
          status)  COMPREPLY=($(compgen -W "--json --no-color --help" -- "${cur}")) ;;
        esac
      fi
      ;;

    chat)
      if [[ $cword -eq 2 ]]; then
        COMPREPLY=($(compgen -W "interactive prompt" -- "${cur}"))
      else
        local chat_flags="--model --provider --system --auto-approve --no-markdown --max-budget-usd --incognito --continue --resume --fork --add-dir --personality --json --no-color --help"
        case "${words[2]}" in
          interactive) COMPREPLY=($(compgen -W "${chat_flags}" -- "${cur}")) ;;
          prompt)      COMPREPLY=($(compgen -W "--output-format --max-turns ${chat_flags}" -- "${cur}")) ;;
        esac
      fi
      ;;

    memory)
      if [[ $cword -eq 2 ]]; then
        COMPREPLY=($(compgen -W "list add forget search clear" -- "${cur}"))
      else
        case "${words[2]}" in
          list)   COMPREPLY=($(compgen -W "--global --json --no-color --help" -- "${cur}")) ;;
          add)    COMPREPLY=($(compgen -W "--global --json --no-color --help" -- "${cur}")) ;;
          forget) COMPREPLY=($(compgen -W "--global --json --no-color --help" -- "${cur}")) ;;
          search) COMPREPLY=($(compgen -W "--json --no-color --help" -- "${cur}")) ;;
          clear)  COMPREPLY=($(compgen -W "--global --yes --json --no-color --help" -- "${cur}")) ;;
        esac
      fi
      ;;

    plan)
      if [[ $cword -eq 2 ]]; then
        COMPREPLY=($(compgen -W "interactive" -- "${cur}"))
      else
        COMPREPLY=($(compgen -W "--model --provider --no-markdown --json --no-color --help" -- "${cur}"))
      fi
      ;;

    swarm)
      if [[ $cword -eq 2 ]]; then
        COMPREPLY=($(compgen -W "start list show" -- "${cur}"))
      else
        case "${words[2]}" in
          start) COMPREPLY=($(compgen -W "--model --json --no-color --help" -- "${cur}")) ;;
          list)  COMPREPLY=($(compgen -W "--json --no-color --help" -- "${cur}")) ;;
          show)  COMPREPLY=($(compgen -W "--json --no-color --help" -- "${cur}")) ;;
        esac
      fi
      ;;

    commit)
      if [[ $cword -eq 2 ]]; then
        COMPREPLY=($(compgen -W "generate" -- "${cur}"))
      else
        COMPREPLY=($(compgen -W "--all --amend --yes --model --provider --json --no-color --help" -- "${cur}"))
      fi
      ;;

    pr)
      if [[ $cword -eq 2 ]]; then
        COMPREPLY=($(compgen -W "create" -- "${cur}"))
      else
        COMPREPLY=($(compgen -W "--base --draft --yes --push --no-push --token --model --provider --json --no-color --help" -- "${cur}"))
      fi
      ;;

    review)
      if [[ $cword -eq 2 ]]; then
        COMPREPLY=($(compgen -W "diff" -- "${cur}"))
      else
        COMPREPLY=($(compgen -W "--staged --base --pr --fix --yes --token --model --provider --json --no-color --help" -- "${cur}"))
      fi
      ;;

    gaia)
      if [[ $cword -eq 2 ]]; then
        COMPREPLY=($(compgen -W "status" -- "${cur}"))
      else
        COMPREPLY=($(compgen -W "--port --host --json --no-color --help" -- "${cur}"))
      fi
      ;;

    schedule)
      if [[ $cword -eq 2 ]]; then
        COMPREPLY=($(compgen -W "list show add remove logs" -- "${cur}"))
      else
        case "${words[2]}" in
          list)   COMPREPLY=($(compgen -W "--active --limit --json --no-color --help" -- "${cur}")) ;;
          show)   COMPREPLY=($(compgen -W "--json --no-color --help" -- "${cur}")) ;;
          add)    COMPREPLY=($(compgen -W "--function-id --cron --interval --description --json --no-color --help" -- "${cur}")) ;;
          remove) COMPREPLY=($(compgen -W "--yes --json --no-color --help" -- "${cur}")) ;;
          logs)   COMPREPLY=($(compgen -W "--limit --json --no-color --help" -- "${cur}")) ;;
        esac
      fi
      ;;

    completion)
      if [[ $cword -eq 2 ]]; then
        COMPREPLY=($(compgen -W "bash zsh install" -- "${cur}"))
      fi
      ;;

    start)
      COMPREPLY=($(compgen -W "--daemonize --pidfile --logfile --time-limit --log-level --api --no-api --json --no-color --help" -- "${cur}"))
      ;;

    stop)
      COMPREPLY=($(compgen -W "--pidfile --signal --json --no-color --help" -- "${cur}"))
      ;;

    status)
      COMPREPLY=($(compgen -W "--json --no-color --help" -- "${cur}"))
      ;;

    check)
      COMPREPLY=($(compgen -W "--extensions --full --json --no-color --help" -- "${cur}"))
      ;;

    version)
      COMPREPLY=($(compgen -W "--json --no-color --help" -- "${cur}"))
      ;;

    dream)
      COMPREPLY=($(compgen -W "--wait --json --no-color --help" -- "${cur}"))
      ;;

    ask)
      COMPREPLY=($(compgen -W "--json --no-color --help" -- "${cur}"))
      ;;

    *)
      COMPREPLY=($(compgen -W "${global_flags}" -- "${cur}"))
      ;;
  esac

  return 0
}

complete -F _legionio_complete legionio
